import { useMemo,useState } from 'react';
import { Routes,Route,NavLink,useNavigate } from 'react-router-dom';
import { Canvas } from '@react-three/fiber';
import { Float,OrbitControls,Stars,Text } from '@react-three/drei';
import { Award,BookOpen,BrainCircuit,ChevronRight,Gamepad2,GraduationCap,Languages,Mic,Play,Volume2 } from 'lucide-react';
import { languages,partsOfSpeech,patternFamilies,recommendation,tsiStages } from './learning';

const nav=[['/','Hall'],['/training','Training Camp'],['/speaker','Speaker'],['/universe','Universe'],['/credentials','Credentials']];
function Shell({children}:{children:any}){return <div className="app"><header><div className="brand"><span>✦</span><div><b>POLYGLOT HEAVEN</b><small>TSI IMMERSIVE LANGUAGE UNIVERSE</small></div></div><nav>{nav.map(([to,l])=><NavLink key={to} to={to} end={to==='/'}>{l}</NavLink>)}</nav><button className="ai">AI MODE <i>ON</i></button></header><main>{children}</main></div>}
function OrbitalHall(){return <div className="scene"><Canvas camera={{position:[0,2.5,8],fov:48}}><color attach="background" args={['#070918']}/><ambientLight intensity={1.2}/><pointLight position={[0,5,2]} intensity={70} color="#8d7dff"/><Stars radius={60} depth={30} count={1600} factor={3}/><Float speed={1.2}><mesh position={[0,1,0]}><torusGeometry args={[2.5,.08,20,120]}/><meshStandardMaterial color="#9d8cff" emissive="#5646d8" emissiveIntensity={2}/></mesh><mesh position={[0,1,0]}><sphereGeometry args={[1.35,64,64]}/><meshStandardMaterial color="#151d3e" metalness={.8} roughness={.2}/></mesh><Text position={[0,1,1.4]} fontSize={.24} color="white">DEVELOPMENT HALL</Text></Float><OrbitControls enablePan={false} minDistance={6} maxDistance={11}/></Canvas><div className="scene-note">Drag to inspect the Hall</div></div>}
function Hall(){const [selected,setSelected]=useState(languages[0]);const rec=useMemo(()=>recommendation(selected),[selected]);const go=useNavigate();return <Shell><section className="hero"><div><span className="eyebrow">WELCOME BACK, GILBERT</span><h1>Your language universe is <em>alive.</em></h1><p>The Hall analyses efficiency, retained mastery, response speed, and TSI coverage to direct your next practice.</p><div className="actions"><button onClick={()=>go('/universe')}><Play size={18}/>Enter Universe</button><button className="ghost" onClick={()=>go('/training')}>View training path</button></div></div><OrbitalHall/></section><section className="grid2"><article className="panel"><div className="panel-title"><BrainCircuit/>Hall Intelligence</div><h2>Practice prescription</h2><div className="recommend"><b>{rec.room}</b><span>Focus: {rec.focus}</span><p>{rec.reason}</p><button onClick={()=>go(rec.room==='Speaker Studio'?'/speaker':'/training')}>Go there <ChevronRight size={16}/></button></div><div className="tsi-strip">{tsiStages.map((s,i)=><div className={i<selected.tsiStage?'done':''} key={s.name}><span>{i+1}</span><small>{s.name}</small></div>)}</div></article><article className="panel"><div className="panel-title"><Languages/>Language profiles</div><div className="lang-list">{languages.map(l=><button className={selected.id===l.id?'active':''} onClick={()=>setSelected(l)} key={l.id}><span className="flag">{l.flag}</span><div><b>{l.name}</b><small>{l.cefr} • {l.coverage}% functional coverage</small></div><i>{l.streak} day streak</i></button>)}</div></article></section><section className="cards">{[['Speaker Studio',Mic,'Record, replay, shadow, and receive pronunciation guidance.'],['Training Camp',GraduationCap,'Complete nine parts-of-speech phases through usable patterns.'],['Pattern Lab',BookOpen,`${patternFamilies.length} functional pattern families.`],['Heaven Universe',Gamepad2,'Explore rooms, buildings, missions, and conversations.']].map(([t,I,d]:any)=><article key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</section></Shell>}
function Training(){return <Shell><div className="page-head"><span className="eyebrow">TSI FUNCTIONAL GRAMMAR</span><h1>Training Camp</h1><p>Nine phases reduce the language into manageable systems while recombining each part into useful speech.</p></div><div className="phase-grid">{partsOfSpeech.map(p=><article key={p.name}><div className="phase-num">{p.phase}</div><div><h3>{p.name}</h3><p>{p.target} high-value words or structures</p><div className="bar"><i style={{width:`${p.mastery}%`}}/></div><small>{p.mastery}% curriculum mastery</small></div></article>)}</div><section className="panel pattern"><h2>Pattern families</h2><div>{patternFamilies.map(x=><span key={x}>{x}</span>)}</div></section></Shell>}
function Speaker(){const [recording,setRecording]=useState(false);const [heard,setHeard]=useState('');const phrase='はじめまして。私はヤンです。';function speak(){const u=new SpeechSynthesisUtterance(phrase);u.lang='ja-JP';speechSynthesis.speak(u)}function record(){const R=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!R){setHeard('Speech recognition is unavailable in this browser.');return}const r=new R();r.lang='ja-JP';r.onstart=()=>setRecording(true);r.onend=()=>setRecording(false);r.onresult=(e:any)=>setHeard(e.results[0][0].transcript);r.start()}return <Shell><div className="page-head"><span className="eyebrow">YAN-SAN • JAPANESE BASIC</span><h1>Speaker Studio</h1><p>Listen, record, replay, compare, and continue into contextual conversation.</p></div><div className="speaker-layout"><article className="yan"><div className="avatar">ヤン</div><h2>Yan-san</h2><p>Your Japanese foundations guide</p><button onClick={speak}><Volume2/>Listen</button></article><article className="panel coach"><span>Target phrase</span><h2>{phrase}</h2><p>Hajimemashite. Watashi wa Yan desu.</p><div className="wave">▁▃▆▂▇▅▃▆▁▅▇▂▃▆▁</div><button className={recording?'danger':''} onClick={record}><Mic/>{recording?'Listening…':'Record response'}</button><div className="transcript"><b>Your transcription</b><p>{heard||'Your spoken response will appear here.'}</p></div></article></div></Shell>}
function Universe(){return <Shell><div className="universe"><Canvas camera={{position:[0,2,9]}}><color attach="background" args={['#03040d']}/><ambientLight intensity={1.1}/><directionalLight position={[4,8,4]} intensity={3}/><Stars count={2500}/>{[-3,0,3].map((x,i)=><group position={[x,0,0]} key={x}><mesh position={[0,1,0]}><boxGeometry args={[2.2,2.2,2.2]}/><meshStandardMaterial color={['#17284f','#37255e','#17443e'][i]} metalness={.5}/></mesh><Text position={[0,1,1.12]} fontSize={.24}>{['HOME DISTRICT','LANGUAGE CITY','IMMERSION GATE'][i]}</Text></group>)}<OrbitControls/></Canvas><div className="universe-ui"><span>HEAVEN UNIVERSE • SEASON ONE</span><h1>A living city built around language missions</h1><p>Every room connects objects, characters, audio, and consequences to a TSI objective.</p><button><Play/>Begin Episode One</button></div></div></Shell>}
function Credentials(){return <Shell><div className="page-head"><span className="eyebrow">VERIFIABLE ACHIEVEMENT</span><h1>Badges and certificates</h1><p>Credentials describe completed curriculum and demonstrated skills without presenting game completion as general fluency.</p></div><div className="credential-grid">{['Positive Transfer','Frequency Lexicon','Functional Grammar','Task-Based Speaker','Scaffolded Immersion','Pathway Certificate'].map((x,i)=><article key={x}><div className="seal"><Award/></div><h3>{x}</h3><p>{i===5?'Issued after the complete assessed pathway.':'Issued after evidence-based mastery criteria are met.'}</p><small>Credential ID • public verification • LinkedIn metadata</small></article>)}</div></Shell>}
export default function App(){return <Routes><Route path="/" element={<Hall/>}/><Route path="/training" element={<Training/>}/><Route path="/speaker" element={<Speaker/>}/><Route path="/universe" element={<Universe/>}/><Route path="/credentials" element={<Credentials/>}/><Route path="*" element={<Hall/>}/></Routes>}
